### ISSUE TITLE
Connection source code

### ISSUE THREAD

**Issue by NuclearPhoenixx** [nibasya/CO2-mini-GUI#1]
Hey there,

thanks for the software. Is there any source code? Also, how does the program connect to the CO2 monitor? Is there a serial connection or something like that?

Thanks

**Comment by nibasya** [comment]
The device is recognized as HID device. The ID for the device is: Vender ID=0x04D9, Product ID=0xA052.
Sorry, the code is not open, but you can see an example of connection / access to CO2 monitor at: https://github.com/fuket/CO2miniReader

**Comment by NuclearPhoenixx** [comment]
I see, thanks!
